runtime: custom
env: flex

env_variables:
  MYSQL_CONNECTION: proxyuser@unix(/cloudsql/revelsample:asia-northeast1:revelsampledb)/gormsample

beta_settings:
  cloud_sql_instances: revelsample:asia-northeast1:revelsampledb